config/routes.rb
SignOn::Application.routes.draw do
  
  # scope constraints: lambda { |r| r.env['warden'].user.nil? } do
  #   get 'signup' => 'users#new', as: :signup
  #   get 'signin' => 'sessions#new', as: :signin
  # end
  
  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'signout' => 'sessions#destroy', as: :signout
  
  get 'account' => 'users#show', as: :account
  
  root to: 'sessions#new'
  
  resources :users, except: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :password, on: :create
  validates :email, presence: true, format: { with: /@/, message: "is invalid" }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private
  
  def current_user
    warden.user
  end
  helper_method :current_user
  
  def warden
    env['warden']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash.now.alert = warden.message if warden.message.present?
  end
  
  def create
    user = warden.authenticate!
    redirect_to account_path, notice: t('auth.success')
  end
  
  def destroy
    warden.logout
    redirect_to root_url, notice: t('auth.logout')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_registration_params)
    if @user.save!
      warden.set_user @user
      redirect_to account_path, notice: t('auth.registration.success')
    else
      # flash.now.alert = t('auth.registration.failure')
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes!(user_update_params)
      redirect_to account_path, notice: t('auth.registration.update.success')
    else
      flash.now.alert = t('auth.registration.update.failure')
      render :edit
    end
  end
  
  def show
    @user = current_user
  end
  
private
  
  def user_registration_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_update_params
    allowed = :name, :email, :password, :password_confirmation
    # allowed << :role if current_user.admin?
    params.require(:user).permit(allowed)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Sign On", root_path, :class => 'brand'
%ul.nav.pull-right
  - if current_user
    %li= link_to current_user.name || current_user.email, account_path
    %li= link_to "Sign out", signout_path
  - else
    %li= link_to "Sign up", signup_path
    %li= link_to "Sign in", signin_path

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Sign On"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/users/new.html.haml
%h1 Sign up

= simple_form_for(User.new, html: {class: 'form-horizontal' }) do |f|
  = f.input :name
  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :password_confirmation, label: "Confirm", required: true
  = f.button :submit

app/views/users/show.html.haml
%h1= @user.name
%p= "Hi, #{@user.username}"
%p= @user.email